# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e51dc5e66f2bee00ab399b1993ae378a22419cf8736a0b4f98f29598d1d4c4dc092ab1d81c3fb94fc320018b5fc5ae3c3ba26e4a3bf2f79217cbd3cb4f127b1b

test:
  secret_key_base: 9340fb15d94e2e4876a3cc9b0fb8e7c257b8786b9b861c9d8f89c0850c839168dc6f4575be59259234736d38792f4af7b93a695bfbde0aa69340bf14a16fb3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
